[package]
name = "vr-screen-cap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
wgpu-hal = { version = "0.13.1", features = ["vulkan"] }
ash = "0.37.0+1.3.209"
ash-window = "0.10.0"
winit = "0.26"
pollster = "0.2"
env_logger = "0.9"
mint = "0.5.9"
bytemuck = { version = "1.10.0", features = [ "derive" ] }


[dependencies.windows]
version = "0.38.0"
features = [
    "alloc",
    "Win32_System_Memory",
    "Win32_Security",
    "Win32_Foundation"
]