[package]
name = "vr-screen-cap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
wgpu-hal = { version = "0.13.1", features = ["vulkan"] }
ash = "0.37.0"
ash-window = "0.10.0"
winit = "0.26"
mint = "0.5.9"
cgmath = { version = "0.18.0", features=["mint"] }
openxr = { version = "0.16.0", features=["static"] }
bytemuck = { version = "1.10.0", features = [ "derive" ] }
tray-item = "0.7.0"
dhat = { version = "0.3.0", optional = true }
log4rs = "1.1.1"
log = "0.4.17"
log-panics = { version = "2.1.0", features=["with-backtrace"] }

[dependencies.windows]
version = "0.38.0"
features = [
    "alloc",
    "Win32_System_Memory",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D", 
    "Win32_Graphics_Dxgi"
]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[features]
dhat-heap = ["dep:dhat"]